[features]
seeds = false

[programs.localnet]
chaintrix_solana = "Agi74KZH6XY5fKPycWtg9X5g4RgfPZpNNmKodLCXDA7q"

[programs.devnet]
chaintrix_solana = "Agi74KZH6XY5fKPycWtg9X5g4RgfPZpNNmKodLCXDA7q"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
