export const COLORS: { [id: string]: any } = {
    "R": {
        name: "red",
        number: 0
    },
    "G": {
        name: "green",
        number: 1
    },
    "B": {
        name: "blue",
        number: 2
    },
    "Y": {
        name: "yellow",
        number: 3
    },
}

export const CARDS: { [id: string]: string } = {
    "1": "RYYBRB",
    "2": "BRRBYY",
    "3": "YRRBBY",
    "4": "BYRBRY",
    "5": "RYYRBB",
    "6": "YRBYBR",
    "7": "RBBYRY",
    "8": "YBBRYR",
    "9": "RYBRBY",
    "10": "BYYRBR",
    "11": "YRRBYB",
    "12": "BRRYBY",
    "13": "YBBYRR",
    "14": "BRRYYB",
    "15": "RGGRYY",
    "16": "YRRYGG",
    "17": "RYYGRG",
    "18": "GYYRGR",
    "19": "YRRGYG",
    "20": "GRRYGY",
    "21": "YGGRRY",
    "22": "GYYGRR",
    "23": "RGGYYR",
    "24": "BGGBRR",
    "25": "RBBGGR",
    "26": "GRRGBB",
    "27": "GRRBGB",
    "28": "GBBRRG",
    "29": "BRRGBG",
    "30": "RBBRGG",
    "31": "YGGRYR",
    "32": "GRYGYR",
    "33": "RGGYRY",
    "34": "RGYRYG",
    "35": "YGRYRG",
    "36": "BGGRBR",
    "37": "RBBGRG",
    "38": "GBBRGR",
    "39": "GRBGBR",
    "40": "BRGBGR",
    "41": "RGGBRB",
    "42": "RBGRGB",
    "43": "BYYGGB",
    "44": "YBGYGB",
    "45": "GYYBBG",
    "46": "YGGBYB",
    "47": "YBBYGG",
    "48": "BGGBYY",
    "49": "GYYGBB",
    "50": "BYGBGY",
    "51": "GBYGYB",
    "52": "BGGYBY",
    "53": "BYYGBG",
    "54": "GYYBGB",
    "55": "YBBGYG",
    "56": "GBBYGY"
}